# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'SpotItApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotItApp
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'SpotItAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotItAppUITests' do
    # Pods for testing
  end

end
